name: Check missing po4a entries

on:
  pull_request:
    branches: [main]

env:
  PO4A_VERSION: "0.73"
  PO4A_GH_URL: https://github.com/mquinson/po4a/releases/download

jobs:
  check_po4a:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Install po4a
        run: ./tools/generate_po4a_entries.sh

      - name: Check if translations require updating
        run: |
          if [[ `git status --porcelain` ]]; then
            git diff --color=always
            echo "There are uncommited changes to po4a entries, see the output above."
            exit 1
          fi
